site_name: {wacc.io} | Cost of capital for the cloud
theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/wacc-icon-white.svg
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
extra_css:
  - stylesheets/custom.css
extra_javascript:
  - js/recaptcha.js
repo_name: pax1a/wacc
repo_url: https://github.com/pax1a/wacc
google_analytics:
  - UA-158202007-1
  - auto
nav:
  - Home: index.md
  - Getting started: 
    - Installation: getting-started.md
  - API:
    - API access: api-access.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
