site_name: wacc
theme:
  name: material
  favicon: img/favicon.png
extra_css:
  - stylesheets/custom.css
repo_name: pax1a/wacc
repo_url: https://github.com/pax1a/wacc
google_analytics:
  - UA-158202007-1
  - auto
