site_name: Docs
theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/wacc-icon-white.svg
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
extra_css:
  - stylesheets/custom.css
repo_name: pax1a/wacc
repo_url: https://github.com/pax1a/wacc
google_analytics:
  - UA-158202007-1
  - auto
nav:
  - Home: index.md
  - Docs: index.md
