name: build docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: ls -a -l
      - run: sed -i 's/{{ API_ENDPOINT }}/'"$secrets.API_ENDPOINT"'/' ./docs/js/recaptcha.js
      - run: mkdocs gh-deploy --force
